name = "newsnow"
pages_build_output_dir = "dist"
compatibility_date = "2025-07-10"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "d0f5d258-1e79-48ea-9501-2c92ac0870aa"      # 替换为你创建的数据库 ID
